//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracts
    {
        public int con_ID { get; set; }
        public int con_o_ID { get; set; }
        public int con_cl_ID { get; set; }
        public System.DateTime con_signing_date { get; set; }
        public System.DateTime con_finish_date { get; set; }
        public int con_sum { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Offers Offers { get; set; }
    }
}
