//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLib
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BanksDBV2Entities : DbContext
    {
        public BanksDBV2Entities()
            : base("name=BanksDBV2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Banks> Banks { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<ClientType> ClientType { get; set; }
        public virtual DbSet<Conditions> Conditions { get; set; }
        public virtual DbSet<Contracts> Contracts { get; set; }
        public virtual DbSet<Offers> Offers { get; set; }
        public virtual DbSet<OfferType> OfferType { get; set; }
    }
}
