//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Offers()
        {
            this.Contracts = new HashSet<Contracts>();
        }
    
        public int o_ID { get; set; }
        public int o_b_ID { get; set; }
        public int o_c_ID { get; set; }
        public string o_name { get; set; }
        public double o_percentage { get; set; }
        public int o_ot_ID { get; set; }
    
        public virtual Banks Banks { get; set; }
        public virtual Conditions Conditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contracts> Contracts { get; set; }
        public virtual OfferType OfferType { get; set; }
    }
}
